name: 'Setup Bicep'
description: 'Installs the Bicep CLI'
author: 'Anthony Martin'
branding:
  icon: hexagon
  color: yellow
inputs:
  version:
    required: false
    description: 'The version of Bicep to use (defaults to latest)'
runs:
  using: 'node12'
  main: 'dist/index.js'
